/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CompanySymbolRouteImport } from './routes/company.$symbol'
import { Route as SectorIdRouteImport } from './routes/sector.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanySymbolRoute = CompanySymbolRouteImport.update({
  id: '/company/$symbol',
  path: '/company/$symbol',
  getParentRoute: () => rootRouteImport,
} as any)
const SectorIdRoute = SectorIdRouteImport.update({
  id: '/sector/$id',
  path: '/sector/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/company/$symbol': typeof CompanySymbolRoute
  '/sector/$id': typeof SectorIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/company/$symbol': typeof CompanySymbolRoute
  '/sector/$id': typeof SectorIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/company/$symbol': typeof CompanySymbolRoute
  '/sector/$id': typeof SectorIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/company/$symbol' | '/sector/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/company/$symbol' | '/sector/$id'
  id: '__root__' | '/' | '/company/$symbol' | '/sector/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompanySymbolRoute: typeof CompanySymbolRoute
  SectorIdRoute: typeof SectorIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company/$symbol': {
      id: '/company/$symbol'
      path: '/company/$symbol'
      fullPath: '/company/$symbol'
      preLoaderRoute: typeof CompanySymbolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sector/$id': {
      id: '/sector/$id'
      path: '/sector/$id'
      fullPath: '/sector/$id'
      preLoaderRoute: typeof SectorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompanySymbolRoute: CompanySymbolRoute,
  SectorIdRoute: SectorIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
